version: '3.4'

services:
  docker-mongo-express:
    image: docker-mongo-express
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]